version: '3'

services:
  reverse-proxy:
    image: traefik:v2.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jobs_server.backend.server.port=80"

      - "traefik.http.routers.jobs_server.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.jobs_server-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.jobs_server.middlewares=jobs_server-strip-prefix@docker"
